version: "3.8"
services:
  web:
    build: .
    restart: always
    ports:
      - '3000:3000'
    expose:
      - '3000'
    depends_on:
      - 'db'
    links:
      - 'db'
    environment:
      DB_HOST: 'db'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db57:/var/lib/mysql
# Names our volume
volumes:
  db57:
